<Project Sdk="Microsoft.NET.Sdk">
	
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>True</UseWPF>
        <RootNamespace>FrostyEditor</RootNamespace>
        <AssemblyName>FrostyEditor</AssemblyName>
        <ApplicationIcon>AppIcon.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <SignAssembly>false</SignAssembly>
        <AssemblyOriginatorKeyFile>FrostyEditor.pfx</AssemblyOriginatorKeyFile>
        <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
        <Platforms>x64</Platforms>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AssemblyVersion>1.0.7.1</AssemblyVersion>
        <FileVersion>1.0.7.1</FileVersion>
    </PropertyGroup>
    
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Final|x64' ">
        <OutputPath>bin\Release\Final\</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <Optimize>true</Optimize>
        <DebugType>portable</DebugType>
        <PlatformTarget>x64</PlatformTarget>
        <ErrorReport>prompt</ErrorReport>
        <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
        <UseVSHostingProcess>false</UseVSHostingProcess>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Developer - Debug|x64'">
        <DebugSymbols>true</DebugSymbols>
        <OutputPath>bin\Developer\Debug\</OutputPath>
        <DefineConstants>TRACE;DEBUG;FROSTY_DEVELOPER</DefineConstants>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugType>portable</DebugType>
        <PlatformTarget>x64</PlatformTarget>
        <ErrorReport>prompt</ErrorReport>
        <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Alpha|x64'">
        <OutputPath>bin\Release\Alpha\</OutputPath>
        <DefineConstants>TRACE;FROSTY_ALPHA</DefineConstants>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Optimize>true</Optimize>
        <DebugType>portable</DebugType>
        <PlatformTarget>x64</PlatformTarget>
        <UseVSHostingProcess>false</UseVSHostingProcess>
        <ErrorReport>prompt</ErrorReport>
        <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
    
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Beta|x64' ">
        <OutputPath>bin\Release\Beta\</OutputPath>
        <DefineConstants>TRACE;FROSTY_BETA</DefineConstants>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Optimize>true</Optimize>
        <DebugType>portable</DebugType>
        <PlatformTarget>x64</PlatformTarget>
        <UseVSHostingProcess>false</UseVSHostingProcess>
        <ErrorReport>prompt</ErrorReport>
        <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
    
    <ItemDefinitionGroup>
        <!-- Enable `GeneratePathProperty` for all `PackageReference`s. -->
        <PackageReference ExcludeAssets="runtime" GeneratePathProperty="true" />
    </ItemDefinitionGroup>
       
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>
       
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <ItemGroup>
            <ThirdPartyFolder Include="$(SolutionDir)FrostyEditor\$(OutDir)ThirdParty\" />
        </ItemGroup>
         
        <Copy SourceFiles="$(PkgNewtonsoft_Json)\lib\net6.0\Newtonsoft.Json.dll" DestinationFolder="@(ThirdPartyFolder)" />
    </Target>
       
    <ItemGroup>
        <None Include="app.manifest">
            <SubType>Designer</SubType>
        </None>
        <None Include="Properties\app.manifest" />
        <None Include="Properties\Settings.settings">
        <Generator>SettingsSingleFileGenerator</Generator>
        <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
        <AppDesigner Include="Properties\" />
    </ItemGroup>
    <ItemGroup>
        <None Include="App.config" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\FrostyHash\FrostyHash.csproj" />
        <ProjectReference Include="..\FrostyModSupport\FrostyModSupport.csproj" />
        <ProjectReference Include="..\FrostyPlugin\FrostyCore.csproj" />
        <ProjectReference Include="..\FrostySdk\FrostySdk.csproj" />
        <ProjectReference Include="..\FrostyControls\FrostyControls.csproj" />
    </ItemGroup>
    
    <ItemGroup>
    <Resource Include="AppIcon.ico" />
    <Resource Include="Images\**\*" />
    <Resource Include="Shaders\ShaderTemplate.txt" />
    <Resource Include="ChangeLog.txt" />
    <Resource Include="Credits.txt" />
      
    <Content Include="Resources\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Shaders\*.bin" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Shaders\*.xml" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Shaders\shaders.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="ThirdParty\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="ThirdParty\FrostyMovie.dll" Condition=" '$(Configuration)' == 'Developer - Debug' " />
    </ItemGroup>
	
</Project>