<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <AssemblyTitle>BlankPlugin</AssemblyTitle>
    <Product>BlankPlugin</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Developer - Debug|x64' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Alpha|x64' ">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="Images\AntStateAssetFileType.png" />
    <None Remove="Images\Eye.png" />
    <None Remove="Images\Instances.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrostyControls\FrostyControls.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\FrostyPlugin\FrostyCore.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\FrostySdk\FrostySdk.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\MeshSetPlugin\MeshSetPlugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Codecs\" />
    <Folder Include="Profiles" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\AntStateAssetFileType.png" />
    <Resource Include="Images\Eye.png" />
    <Resource Include="Images\Instances.png" />
	<Resource Include="Images\RigidMeshFileType.png" />
	<Resource Include="Images\SkinnedMeshFileType.png">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<PluginFiles Include="$(TargetDir)$(ProjectName).*" />
		</ItemGroup>
		<Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(SolutionDir)FrostyEditor\$(OutDir)Plugins\" />

		<Copy SourceFiles="$(ProjectDir)AssImp\assimp.dll;$(ProjectDir)AssImp\AssimpNet.dll"
			  DestinationFolder="$(SolutionDir)FrostyEditor\$(OutDir)Plugins\" />
	</Target>
	
</Project>
